name: update pmd binaries and rulesets to latest

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    name: upgrade pmd binaries and rulesets
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v4
    - name: install bsdtar
      run: |
        sudo apt update
        sudo apt install -y libarchive-tools
    - name: run pmd upgrade script
      run: |
        source bin/update.sh
        
        # make version available to next steps
        echo "VERSION=${VERSION}" >> "$GITHUB_OUTPUT"
    - name: commit changes
      run: |
        # configure git
        git config user.name github-actions
        git config user.email github-actions@github.com

        # create a new branch
        git checkout -b chore/upgrade-pmd-${VERSION}
        
        # commit changes
        git add .
        git commit -m "upgrade pmd binaries and rulesets to ${VERSION}"

        # push changes
        git push --force origin chore/upgrade-pmd-${VERSION}

        # create a pull request
        gh pr create --title "upgrade pmd binaries and rulesets to ${VERSION}" --body "upgrade pmd binaries and rulesets to ${VERSION}" --base main --head chore/upgrade-pmd-${VERSION}